cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path(
        'remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove',
    ),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('search/', views.search_products, name='product_search'),
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.category_products, name='product_list_by_category'),  # Updated this to use the new view
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('twitter/', views.TwitterView.as_view(), name='twitter'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.utils.html import format_html
from easy_thumbnails.files import get_thumbnailer
from django.core.exceptions import ValidationError
from django.utils.text import slugify
from unidecode import unidecode
from mptt.models import MPTTModel, TreeForeignKey

def item_upload_location(instance, filename):
    item_name = instance.product.name.lower().replace(" ", "-")  # Use `product` instead of `item`
    file_name = filename.lower().replace(" ", "-")
    return f"item_images/{item_name}/{file_name}"

def validate_file_size(value):
    limit = 104857600  # 100 MB
    if value.size > limit:
        raise ValidationError('Файл слишком большой. Максимальный размер 100 MB.')




class Category(MPTTModel):
    name = models.CharField('Название', max_length=200)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    parent = TreeForeignKey(
        'self', 
        on_delete=models.SET_NULL, 
        related_name='subcategories', 
        null=True, blank=True, 
        verbose_name='Родительская категория'
    )

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return f'{self.parent.name + " -> " if self.parent else ""}{self.name}'
    
    def save(self, *args, **kwargs):
        if not self.slug:
            # Генерация slug на основе имени категории
            self.slug = slugify(unidecode(self.name))
            
            # Проверка на уникальность slug
            original_slug = self.slug
            num = 1
            while Category.objects.filter(slug=self.slug).exists():
                self.slug = f'{original_slug}-{num}'
                num += 1
        
        super().save(*args, **kwargs)

class Product(models.Model):
    category = models.ForeignKey(
        
        Category,
        related_name='products',
        on_delete=models.CASCADE,
        verbose_name='Категория товара',
    )
    name = models.CharField('Название',max_length=200)
    slug = models.SlugField(max_length=200,unique=True, blank=True)
    image = models.ImageField('Главное фото',
        upload_to='products/%Y/%m/%d',)
    video = models.FileField("Видео", upload_to='item_videos/', blank=True, null=True, validators=[validate_file_size])
    description = models.TextField('Описание',blank=True)
    price = models.DecimalField('Цена',max_digits=10, decimal_places=2)
    available = models.BooleanField('Отображать?',default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]
        verbose_name = "Товар"
        verbose_name_plural = "Товары"


    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # Если slug пустой, генерируем его из имени категории
        if not self.slug:
            # Используем unidecode для транслитерации имени
            self.slug = slugify(unidecode(self.name))
            
            # Проверяем, чтобы slug был уникальным
            num = 1
            original_slug = self.slug
            while Product.objects.filter(slug=self.slug).exists():
                self.slug = f'{original_slug}-{num}'
                num += 1

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField('Фотография',upload_to=item_upload_location, null=True, blank=True)
    order = models.PositiveIntegerField(default=0)
    
    def image_thumbnail(self):
        if self.image:
            thumbnail_url = get_thumbnailer(self.image)['admin_thumbnail'].url
            return format_html('<img src="{}" width="150" height="150" />', thumbnail_url)
        return "Нет изображения"

    image_thumbnail.short_description = 'Предпросмотр фотографии'

    def __str__(self):
        return f"Фотография товара: {self.product.name}"
    
    class Meta:
        verbose_name = "Фотографии товара"
        verbose_name_plural = "Фотографии товара"

shop/views.py
from django.shortcuts import get_object_or_404, render

from cart.forms import CartAddProductForm
from .models import Category, Product

from cart.cart import Cart
from cart.forms import CartAddProductForm

from django.db.models import Q

from django.core.paginator import Paginator
from django.http import JsonResponse
from django.template.loader import render_to_string


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    query = request.GET.get('q')  # Получаем поисковый запрос
    products = Product.objects.filter(available=True)

    all_item_count = products.count()  # Подсчитываем количество всех товаров
    cart_product_form = CartAddProductForm()

    # Если есть поисковый запрос, фильтруем товары по названию
    if query:
        products = products.filter(Q(name__icontains=query))

    # Если slug категории присутствует, фильтруем товары по этой категории
    if category_slug:
        selected_category = get_object_or_404(Category, slug=category_slug)
        category_items = {
            selected_category.name: list(
                products.filter(category=selected_category, available=True)
            )
        }
    else:
        # Если slug отсутствует, выводим все товары по категориям
        if query:
            # Фильтруем товары в рамках всех категорий по поисковому запросу
            category_items = {
                category.name: list(
                    products.filter(category=category, available=True)
                ) for category in categories if products.filter(category=category).exists()
            }
        else:
            # Если нет поискового запроса, показываем все товары
            category_items = {
                category.name: list(
                    Product.objects.filter(category=category, available=True)
                ) for category in categories
            }
    
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True}
        )


# Пагинация по категориям
    paginator = Paginator(categories, 3)  # Пагинация по 3 категории на страницу
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)

    # Получаем все товары для отображаемых на странице категорий
    category_items = {
        category.name: list(Product.objects.filter(category=category, available=True)) for category in page_obj
    }

    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True}
        )

    cart_items = {str(item['product'].id): item['quantity'] for item in cart}  # Собираем информацию о товарах в корзине

    # AJAX запрос для подгрузки следующих категорий
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        html = render_to_string('shop/product/test.html', {'category_items': category_items})
        return JsonResponse({'html': html, 'cart_items': cart_items, 'has_next': page_obj.has_next()})

    return render(
        request,
        'shop/product/list.html',
        {
            'category': category,
            'category_items': category_items,  # Пагинированные категории и их товары
            'all_item_count': all_item_count,
            'categories': page_obj,  # Пагинация категорий
            'categories_objects':categories,
            'cart_product_form': cart_product_form,
            'cart': cart,
            'products': products,
        },
    )


def product_detail(request, id, slug):
    product = get_object_or_404(
        Product, id=id, slug=slug, available=True
    )
    cart_product_form = CartAddProductForm()
    return render(
        request,
        'shop/product/detail.html',
        {
            'product': product, 
            'cart_product_form': cart_product_form,
            
        },
    )


from django.views import View

class TwitterView(View):

    def get(self, request, forum, *args, **kwargs):
        # Template to render
        template_name = "shop/product/list.html"
        page_template = "shop/product/test.html"

        # Fetch all products
        products = Product.objects.all()

        # Context data
        data = {
            'products': products,
        }

        # Check for AJAX request
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            template_name = page_template

        # Render the template with context
        return render(request, template_name, data)
    
def category_products(request, category_slug):
    # Get the selected category
    category = get_object_or_404(Category, slug=category_slug)
    
    # Filter products by the selected category
    products = Product.objects.filter(category=category, available=True)
    
    # Initialize the form for adding to cart
    cart_product_form = CartAddProductForm()
    
    # Render the page
    return render(
        request, 
        'shop/product/category_list.html', 
        {
            'category': category, 
            'products': products,
            'cart_product_form': cart_product_form,
        }
    )

def search_products(request):
    query = request.GET.get('q', '')  # Get search query
    products = Product.objects.filter(available=True)  # Get available products

    if query:
        # Filter products by name based on query
        products = products.filter(Q(name__icontains=query))

    # Organize products by category
    categories = Category.objects.all()
    category_items = {
        category.name: list(
            products.filter(category=category, available=True)
        ) for category in categories if products.filter(category=category).exists()
    }

    all_item_count = products.count()  # Count all matching products
    cart_product_form = CartAddProductForm()

    return render(
        request,
        'shop/product/search_results.html',  # New template to display search results
        {
            'category_items': category_items,  # Products grouped by category
            'query': query,  # To display search query
            'all_item_count': all_item_count,  # To show the total number of products found
            'cart_product_form': cart_product_form,
        },
    )

shop/templates/shop/base.html
{% load custom_filters %}
{% load static %}
{% csrf_token %}

<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block tittle %}{% endblock tittle %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  
  <style>
    /* Стили для бегущей строки */
    .marquee-container {
      width: 85%; /* На всю ширину экрана */
      height: 50px;
      overflow: hidden;
      background-color: #f8f9fa;
      position: absolute;
      top: 60px; /* Иконка будет ровно на 150px ниже логотипа */
      left: 15px;
    }

    .marquee-text {
      display: inline-block;
      white-space: nowrap;
      position: absolute;
      animation: marquee 10s linear infinite;
    }

    /* Анимация для движения слева направо */
    @keyframes marquee {
      0% {
        left: -100%; /* Текст начинает за пределами слева */
      }
      100% {
        left: 100%; /* Двигается за пределы справа */
      }
    }

    
    .logo-container {
      position: relative;
    }
    
    .whatsapp-image {
      position: absolute;
      top: 60px; /* Иконка будет ровно на 150px ниже логотипа */
      left: 15px;
    }
    
    

  </style>
  {% block links %}
  {% endblock links %}
  
</head>
<body>




  <!-- Навигационное меню для Desktop-->
  <nav id="navbar-desktop" class="navbar navbar-expand-lg navbar-light bg-light shadow-sm py-3">
    <div class="container">
      <!-- Лого -->
      <div class="logo-container">
        <a class="navbar-brand" href="/">
          <img src="{% static 'img/logo.jpeg' %}" alt="Лого" width="80" height="80" class="d-inline-block align-text-top img-fluid">
        </a>
        <!-- Дополнительная картинка под логотипом -->
        <a href="https://wa.me/77781381976?text=Здравствуйте!%0AПишу%20вам%20с%20сайта%20iska.kz">
          <img src="{% static 'img/whatsapp.png' %}" alt="Ватсап" width="50" height="50" class="img-fluid whatsapp-image">
        </a>
      </div>
      

      <!-- Весь контент навбара -->
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <!-- Кнопка "Каталог" с выпадающим списком -->
      <div class="dropdown me-3">
        <a class="btn btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
          Каталог
        </a>
      
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li><a class="dropdown-item" href="{% url 'shop:product_list' %}">Все товары</a></li>
          {% for category in categories_objects %}
            <li><a class="dropdown-item" href="{% url 'shop:product_list_by_category' category.slug %}">{{ category.name }}</a></li>
          {% endfor %}
        </ul>
      </div>
      

        <div class="container mt-4 search-form logo-container" >
          <!-- Поле поиска -->
          <form class="d-flex flex-grow-1 me-3" method="get" action="{% url 'shop:product_search' %}" style="margin-top: 17px;">
            <input class="form-control me-2" type="search" name="q" placeholder="Поиск товаров..." aria-label="Search" style="min-width: 150px;">
            <button class="btn btn-primary" type="submit">Поиск</button>
          </form>

          <!-- Бегущая строка под навбаром -->
          <div class="d-flex justify-content-center align-items-center marquee-container">
            <span class="marquee-text">При заказе от 10 000 тг бесплатная доставка по Алматы</span>
          </div> 
        </div>




        <!-- Кнопка корзины -->
        <div class="d-flex justify-content-end">
          <div class="cart">
            {% with total_items=cart|length %}
              <a href="{% url 'cart:cart_detail' %}" class="btn btn-primary d-flex align-items-center" id="cart-link">
                <i class="fas fa-shopping-cart fa-2x me-2"></i>
                <div class="d-none d-lg-block">
                  {% if total_items == 1 %}
                    <span id="cart-total-items">{{ total_items }}</span> товар
                  {% elif total_items > 1 and total_items < 5 %}
                    <span id="cart-total-items">{{ total_items }}</span> товара
                  {% else %}
                    <span id="cart-total-items">{{ total_items }}</span> товаров
                  {% endif %}
                  <br>
                  <span class="d-block"><span id="cart-total-price">{{ cart.get_total_price |price_format}} </span>₸</span>
                </div>
              </a>

            {% endwith %}
          </div>
        </div>

      </div>
    </div>
    
  </nav>





  
  <!-- Навигационное меню для Mobile -->
  <nav id="navbar-mobile" class="navbar navbar-expand-lg navbar-light bg-light shadow-sm py-3">
    <div class="container-fluid d-flex align-items-center justify-content-between">
      
      <!-- Кнопка "Каталог" с выпадающим списком -->
      <div class="dropdown me-3">
        <a class="btn btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
          Каталог
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li><a class="dropdown-item" href="{% url 'shop:product_list' %}">Все товары</a></li>
          {% for category in categories_objects %}
            <li><a class="dropdown-item" href="{% url 'shop:product_list_by_category' category.slug %}">{{ category.name }}</a></li>
          {% endfor %}
        </ul>
      </div>
  
      <!-- Лого -->
      <a class="navbar-brand" href="#">
        <img src="{% static 'img/logo.jpeg' %}" alt="Лого" width="80" height="80" class="img-fluid">
      </a>
      <a href="https://wa.me/77781381976?text=Здравствуйте!%0AПишу%20вам%20с%20сайта%20iska.kz" class="navbar-brand">
        <img src="{% static 'img/whatsapp.png' %}" alt="Ватсап" width="50" height="50" class="img-fluid">
      </a>
      
      <!-- Кнопка корзины -->
      <div class="cart d-flex align-items-center position-relative">
        <a href="{% url 'cart:cart_detail' %}" class="btn btn-primary d-flex align-items-center position-relative" id="cart-link">
          <i class="fas fa-shopping-cart fa-2x"></i>
          <span id="cart-total-items-new" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
            {% with total_items=cart|length %} {{ total_items }} {% endwith %}
          </span>
        </a>
      </div>
  
      <!-- Поле поиска -->
      <div class="container mt-3 search-form">
        <form class="d-flex flex-grow-1 me-3" method="get" action="{% url 'shop:product_list' %}" style="margin-top: 17px;">
          <input class="form-control me-2" type="search" name="q" placeholder="Поиск товаров..." aria-label="Search" style="min-width: 150px;">
          <button class="btn btn-primary" type="submit">Поиск</button>
        </form>
      </div>
  

  
    </div>
    <div style="width: 80%; margin: 0 auto; display: flex; justify-content: center;">
      <p class="text-center" style="word-wrap: break-word; max-width: 100%;">
        При заказе от 10 000 тг бесплатная доставка по Алматы
      </p>
    </div>
    
  </nav>

  


  {% block content %}
  {% endblock content %}
<!-- Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"></script>
  

  {% comment %} <script src="{% static 'endless-pagination/js/module.endless.js' %}"></script>
  <script src="{% static 'endless-pagination/js/endless-pagination.js' %}"></script> {% endcomment %}

</body>
</html>